[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C",
	"target-cpu=x86-64"
]

[env]
LLAMA_AVX = "ON"
LLAMA_AVX2 = "ON"
LLAMA_FMA = "ON"
LLAMA_F16C = "ON"
LLAMA_NATIVE = "OFF"
LLAMA_STATIC_CRT = "1"
LLAMA_BUILD_SHARED_LIBS = "1"
CMAKE_BUILD_TYPE = "Release"
CMAKE_GGML_OPENMP = "OFF"
CMAKE_GGML_NATIVE = "OFF"
CMAKE_GGML_AVX = "ON"
CMAKE_GGML_AVX2 = "ON"
CMAKE_GGML_FMA = "ON"
CMAKE_GGML_F16C = "ON"
CMAKE_GGML_AVX512 = "OFF"
